# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160805_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publihsher',
            new_name='Publisher',
        ),
    ]
